[package]
name = "block_stm"
version = "0.1.0"
edition = "2021"
authors = ["Hemengjie <njtech_hemengjie@qq.com>"]
description = "An implement of Block-STM"
license = "Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = { version = "0.8.2", features = ["crossbeam-epoch"] }
dashmap = "5.4.0"
num_cpus = "1.13.1"
once_cell = "1.15.0"
rayon = "1.5.3"
thiserror = "1.0.37"
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
rand = "0.8.5"

[dev-dependencies]
criterion = "0.4.0"
rand = "0.8.5"
tracing-appender = "0.2.2"

[[bench]]
name = "benchmark"
harness = false
